#!/usr/bin/env bash
# this script displays only the following fields from /etc/passwd
# username, userid, home directory path for user

while read -r line; do
    echo "$line" | cut -d':' -f 1,3,6
done < /etc/passwd
