#!/usr/bin/env bash
# Bash script that loops from 1 to 10 bad luck for 4th, good luck for the 8th loop, Best School for the other iterations

i=1
while ((i<=10))
do
	if((i==4))
	then 
		echo "bad luck"
	elif((i==8))
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
